package com.rioikeda.newslisten.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1F6FD6)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD8E5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D47)
val md_theme_light_secondary = Color(0xFF555F7F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD9E3FF)
val md_theme_light_onSecondaryContainer = Color(0xFF111C37)
val md_theme_light_tertiary = Color(0xFF6E5C7A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF8DAFF)
val md_theme_light_onTertiaryContainer = Color(0xFF271A33)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_surface = Color(0xFFFBFCFE)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF47474E)
val md_theme_light_outline = Color(0xFF78787E)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1F6)
val md_theme_light_inverseSurface = Color(0xFF2E3133)

val md_theme_dark_primary = Color(0xFFAFD2FF)
val md_theme_dark_onPrimary = Color(0xFF003373)
val md_theme_dark_primaryContainer = Color(0xFF0D4AA9)
val md_theme_dark_onPrimaryContainer = Color(0xFFD8E5FF)
val md_theme_dark_secondary = Color(0xFFBDC7FF)
val md_theme_dark_onSecondary = Color(0xFF263150)
val md_theme_dark_secondaryContainer = Color(0xFF3D4868)
val md_theme_dark_onSecondaryContainer = Color(0xFFD9E3FF)
val md_theme_dark_tertiary = Color(0xFFDCBCED)
val md_theme_dark_onTertiary = Color(0xFF41234E)
val md_theme_dark_tertiaryContainer = Color(0xFF593B67)
val md_theme_dark_onTertiaryContainer = Color(0xFFF8DAFF)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E7)
val md_theme_dark_surface = Color(0xFF191C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E7)
val md_theme_dark_surfaceVariant = Color(0xFF47474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C7CF)
val md_theme_dark_outline = Color(0xFF92919A)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E7)
